In [42]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


import kagglehub

/kaggle/input/datasets/rockinjas123/spam-ham-emails/emails.csv

In [43]:
df = pd.read_csv("/kaggle/input/datasets/rockinjas123/spam-ham-emails/emails.csv")

df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [44]:
df["spam"].value_counts()

spam
0    4360
1    1368
Name: count, dtype: int64

In [45]:
df.drop_duplicates(inplace = True)

df

                                                   text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [46]:
df.isnull().sum()

text    0
spam    0
dtype: int64

# Seperate X and Y Values

In [47]:
x = df.text.values
y = df.spam.values

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [48]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)

# Train ML Algorithm

In [49]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train, ytrain)

MultinomialNB()

In [50]:
x_test = cv.transform(xtest)

model.score(x_test, ytest)

0.9912203687445127

In [51]:
emails = [
    "hey i am lokking for machine learning tutorial in begali language",
    "hey you win an iphone x giveaway for free..."
]

In [52]:
cv_emails = cv.transform(emails)
model.predict(cv_emails)

array([0, 1])